### ISSUE TITLE
As a Athlete, I can see my Athlete Stats - AthleteProfile Component

### ISSUE THREAD

**Issue by williamphelps13** [KickMatch/kick_match_fe#3]
Profile:

1. Name
2. Primary Position
3. Secondary Position
4. Age
5. Zip Code

6. Dominate Foot
5. Height
6. Weight
7. Goals Last Season
8. 40 Yd Dash
9. Vertical Jump
10. Personal Juggling Record
11. Talents - Choose Top 3
- General Defensive Abilities
- Passing Ability
- Agility
- Top Speed
- Off Ball Movement
- Taking Free Kicks
- Taking Corner Kicks
- Shooting
- Leadership
- Dribbling

12. Awards

POSITIONS:
- Goalie
- Fullback
- Sweeper/Stopper
- Center Mid
- Outside Mid
- Striker

**Comment by saberg1** [comment]
Done! Pull Request #17
